### ISSUE TITLE
retarded aboutme code

### ISSUE THREAD

**Issue by xxxOMA** [PaceCodes/PaceCodes#1]
you legit know nothing about java retard

**Comment by PaceCodes** [comment]
as you say, but I still think I know something in that

**Comment by EZZZZ1234** [comment]
Why you both fight? you both are very good at java. why no be friends?

**Comment by PaceCodes** [comment]
idk he thinks I don't know java. I want to be friendly with him but idk about him, he is probably better then me tbh.

**Comment by xxxOMA** [comment]
no you don't LOL 90% of the code in this is pure bullshit

why the abstract Human class retard? legit no abstract methods...
